### ISSUE TITLE
Is there a way to ask user for Camera/Microphone access after they have already denied it on iOS?

### ISSUE THREAD

**Issue by Balasnest** [twilio/video-quickstart-objc#112]
### Description

Is there a way to ask user for Camera/Microphone access after they have already denied it on iOS?

### Steps to Reproduce

1. when user join the video, **Camera/Microphone permission** is asked for the first time. 
2. If deined, is there a way to ask user for permission again like **'Go to Setting'** take the user to setting screen instead of manually going to app setting. Bcz, most of the user doesn't know about that.
3. Opponent User gets blank video screen if other user deined.

#### Video iOS SDK

[e.g. 2.0 via CocoaPods]

#### Xcode

[e.g. 9.2]

#### iOS Version

[e.g. 11.2.6]

#### iOS Device

[e.g. iPhone 8 Plus]

**Comment by ceaglest** [comment]
Hey @Balasnest,

Sorry for the slow response to your question.

> Is there a way to ask user for Camera/Microphone access after they have already denied it on iOS?

No, but you can direct the user to the Settings app to manually grant permission. You can also prevent portions of your app from functioning (such as joining a Room) based upon a lack of permissions at runtime.

Our SDK acts as a "last line of defense", meaning that we will ask for permissions automatically if the user tries to use the camera or microphone. This isn't behavior we've explicitly written, but rather a function of AVCaptureSession for the camera, and AudioUnit for the microphone.

> If deined, is there a way to ask user for permission again like 'Go to Setting' take the user to setting screen instead of manually going to app setting. Bcz, most of the user doesn't know about that.

I believe so, or at least I have done this in past versions of iOS. From what Apple says you should be able to simply open [UIApplicationOpenSettingsURLString](
https://developer.apple.com/documentation/uikit/uiapplicationopensettingsurlstring?language=objc).

```.objc
NSURL *url = [NSURL URLWithString:UIApplicationOpenSettingsURLString];
// Should be true if your app has a settings, including permissions.
if ([[UIApplication sharedApplication] canOpenURL:url]) {
   [[UIApplication sharedApplication] openURL:url];
}
```

Best,
Chris

**Comment by Balasnest** [comment]
Thanks for your response. I have handled the permission at my end.

**Comment by ceaglest** [comment]
Sounds good, let us know if there is anything else you need.
