### ISSUE TITLE
How to show and hide Preview image 

### ISSUE THREAD

**Issue by SusheelYadavAhex** [twilio/video-quickstart-objc#120]
I am using your SDK in one my Objective-C Project . 

My Scenario is , in video calling screen , i have one button to show and hide Preview view. Once user clicks on that button , the preview view should hide from both the participants (from user and recipient end) who have joined the room or call . 

And again ,once he/she clicked on that button , we need to show preview image. Can u please suggest me how this be achievable. 

So far i have tried like this 

```
#pragma mark - Preview Button Action
- (IBAction)PreviewAction:(UIButton *)sender {
    if (sender.selected)
    {
        // show view
        sender.selected = NO;
        [self.localVideoTrack addRenderer:self.previewView];
        [sender setImage:[UIImage imageNamed:@"transparentVideo"] forState:UIControlStateNormal];
    }
    else
    {
        // hide View
        sender.selected = YES;
        [self.localVideoTrack removeRenderer:self.previewView];
        [self.previewView  removeFromSuperview];
        [sender setImage:[UIImage imageNamed:@"hideVideo"] forState:UIControlStateNormal];
        
    }
}
```

But the above code is not working . 

**Note :** 1.  When i am hiding my preview view from one end(user end), my image should not be visible to other participant (recipient end ).
2. I am using this pod version in my application ( pod 'TwilioVideo', '~> 1.3.0' ). 
3. Testing in Xcode 9.3 , IOS 11.3 . 

Waiting for your reply. 

Best Regards
Susheel Yadav.

**Comment by SusheelYadavAhex** [comment]
When i am hiding my preview view from one end(user end), my image should not be visible to other participant (recipient  end ).

**Comment by ceaglest** [comment]
Hi @SusheelYadavAhex,

Sorry for the delayed reply. What you want to do is unpublish your video track when you no longer want the remote party to see it.

You mentioned that you are using our older 1.x SDK. I would strongly recommend upgrading to 2.x because it represents publishing as an asynchronous operation which may succeed or fail. In 1.x if there is an error it is silently swallowed by our SDK.

For 1.x, you should take a look at [TVILocalParticipant removeVideoTrack:](https://twilio.github.io/twilio-video-ios/docs/latest_1.x/Classes/TVILocalParticipant.html#//api/name/removeVideoTrack:). This method will allow you to stop publishing video in a Room. Keep in mind that unless you destroy the LocalVideoTrack then the capturer will continue to capture content.

```objc
// Stops publishing the Track.
[self.room.localParticipant removeVideoTrack:self.localVideoTrack];
// Stop rendering.
[self.localVideoTrack removeRenderer:self.previewView];
// If we are the last owner, destroy the VideoTrack. If this is temporary, you could also keep it around for later but the capturer will continue capturing.
[self.previewView  removeFromSuperview];
```

Best,
Chris

**Comment by SusheelYadavAhex** [comment]
Thanks @ceaglest , 

So far i have tried like this.. 

```
#pragma mark - Show preview button From UI
- (IBAction)videoAction:(UIButton *)sender {
          if (sender.selected)
        {
            // show view
            sender.selected = NO;
            self.localVideoTrack.enabled = YES;
            [sender setImage:[UIImage imageNamed:@"showImage.png"] forState:UIControlStateNormal];
        }
        else
        {
            // hide View
            sender.selected = YES;
            self.localVideoTrack.enabled = NO;
            [sender setImage:[UIImage imageNamed:@"hideImage.png"] forState:UIControlStateNormal];
    
        }
    
}
```

Even it is working fine , does this make any difference in future . If i am doing any thing wrong , please do suggest me . 

Thanks .

**Comment by ceaglest** [comment]
Hi @SusheelYadavAhex,

Sorry that this ticket got lost in the shuffle. In response to your last code snippet, you can just disable the track, but you will still be publishing black frames which uses a non-zero amount of bandwidth. You will also be using the camera, if only to discard the frames.

If you won't be using the video for a long time (or ever again) consider unpublishing the track using the snippet I provided. Disabling video for short periods of time is fine.

Let us know if you have any more questions.

Best,
Chris
