### ISSUE TITLE
Cant render local video

### ISSUE THREAD

**Issue by iqbalpalemad** [twilio/video-quickstart-objc#131]
Hai 

In my ios application The app crashed when i start the preview of local camera. 

Error : 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'The supplied renderer does not conform to the TVIVideoRenderer protocol.'

**Comment by ceaglest** [comment]
Hi @iqbalpalemad,

What kind of renderer are you using? If you try to add a renderer which is not actually a `TVIVideoRenderer` then an exception will be thrown.

Here is how we render local video in the [QuickStart](https://github.com/twilio/video-quickstart-objc/blob/master/ObjCVideoQuickstart/ViewController.m#L118). Note that `previewView` is a `TVIVideoView` that was created in a storyboard.

Regards,
Chris

**Comment by iqbalpalemad** [comment]
my previewView was not implementing TVIVideoView . Now the error has fixed.
