### ISSUE TITLE
IOS and android 

### ISSUE THREAD

**Issue by anasanasanas** [twilio/video-quickstart-objc#18]
when Connect IOS video quick start with android video quick start IOS can see android video call and hear it good but android just hear the voice and no video at all it is just black screen.

**Comment by idelgado** [comment]
@anasanasanas can you provide us with more information about the devices you are using on iOS and Android? This will help us recreate locally and root cause the issue.

**Comment by anasanasanas** [comment]
we tried iPhone 6s for IOS and Samsung A5 for android.

**Comment by idelgado** [comment]
@anasanasanas I'm confident the latest version of our Video library will work with both of these devices.

Please try our new Video SDK:
iOS: https://github.com/twilio/video-quickstart-objc/tree/master
Android: https://github.com/twilio/video-quickstart-android/tree/master

Getting Started: https://www.twilio.com/docs/api/video/getting-started
