### ISSUE TITLE
Privacy Settings in iOS 10

### ISSUE THREAD

**Issue by ron194** [twilio/video-quickstart-objc#23]
Error in iOS 10:
> This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

Solution: http://useyourloaf.com/blog/privacy-settings-in-ios-10/

**Comment by ceaglest** [comment]
@ron194 The latest version of our sample app on `master` has been rewritten to use `TwilioVideo.framework` rather than the old Conversations SDK. This version includes the privacy keys needed on iOS 10.
