### ISSUE TITLE
VoIP is deprecated

### ISSUE THREAD

**Issue by ron194** [twilio/video-quickstart-objc#24]
> Legacy VoIP background mode is deprecated and no longer supported

**Comment by ptankTwilio** [comment]
Hi Ron,
Thanks for reaching out to us.

Yes, Starting iOS 10, VoIP background mode is not supported. We have released new Room based [Video SDK 1.0.0-beta1](https://media.twiliocdn.com/sdk/ios/video/releases/1.0.0-beta1/twilio-video-ios-1.0.0-beta1.tar.bz2). You can use video sdk 1.0.0-beta1, we would love to have your feedbacks.

Thank you,
Piyush Tank

**Comment by ceaglest** [comment]
@ron194 To clarify, our `1.0.0-beta1` release incorrectly tags the signaling connection as a VOIP socket. We will be removing this tagging in a future beta release, but for now I've listed it as a known issue in our [changelog](https://www.twilio.com/docs/api/video/changelogs/ios).

**Comment by ceaglest** [comment]
Hi @ron194,

In `1.0.0-beta8` we've removed any VOIP socket tagging. Check it out if you get a chance.

https://www.twilio.com/docs/api/video/changelogs/ios

Cheers,
Chris
