### ISSUE TITLE
Video Gravity

### ISSUE THREAD

**Issue by gaston23** [twilio/video-quickstart-objc#29]
Hi guys,

![example](https://camo.githubusercontent.com/b7104ebfa444107de321bb5a5ba1131dad20c210/687474703a2f2f7777772e77332e6f72672f54522f637373332d696d616765732f696d675f7363616c652e706e67)

Is it possible to specify gravity to video rendering layers ? I want video previews (mine and remote) to fill the whole view they are covered, cropping as necessary. Current rendered feeds are contained.

Thank you

**Comment by gaston23** [comment]
Hacking the sdk a little I see that setting ````TWCVideoViewContainer```` contentMode to ````UIViewContentModeScaleToFill```` makes the feed go into Fill mode. Sadly, ````UIViewContentModeScaleAspectFill```` doesn't seem to make the video feed Cover, behaves like Fill. :(

**Comment by ceaglest** [comment]
@gaston23 Thanks for writing in!

At the moment, no matter what you set the UIViewContentMode to, our renderers only support `UIViewContentModeScaleAspectFit`. We are aware of this issue, and will be correcting it in a future beta release.

**Comment by ceaglest** [comment]
@gaston23 One more thing to mention, if you use `TVICameraPreviewView` you can get `UIViewContentModeScaleToFill`, `UIViewContentModeScaleAspectFill`, and `UIViewContentModeScaleAspectFit` for your local preview.

**Comment by ceaglest** [comment]
@gaston23 we just released `1.0.0-beta4` which adds support for `UIViewContentModeScaleAspectFill`, and `UIViewContentModeScaleToFill` to `TVIVideoViewRenderer`. Give it a shot in your app and lets us know if you have any issues.

**Comment by gaston23** [comment]
Thank you!

On Tuesday, December 13, 2016, Christopher Eagleston <
notifications@github.com> wrote:
> @gaston23 we just released 1.0.0-beta4 which adds support for
UIViewContentModeScaleAspectFill, and UIViewContentModeScaleToFill to
TVIVideoViewRenderer. Give it a shot in your app and lets us know if you
have any issues.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/pJ_Ri0Cfx1mDfRrh0KvdLsxqozTH9qqKjGrH5mbhpgMe53TtsmqqUGASY5BrRwnsvuI30zV_RqPldcIBjM-I2k2SnhM1nbiaeBxfIjOqR0v5axSL60bGqcmJR8-e1sKRR9Hy6Mq7sG6T7aIvrvsMShoPGBM80w=s0-d-e1-ft#https://github.com/notifications/beacon/AAm5Kfa1_jJkz96_p4T9mSv6NqKWlCvlks5rHxODgaJpZM4KqUTM.gif
>

-- 
Sent from Gmail Mobile

**Comment by girtis** [comment]
Resolved, closing
