### ISSUE TITLE
Disable/Enable Video 

### ISSUE THREAD

**Issue by Abhishek9634** [twilio/video-quickstart-objc#44]
How i can Disable/Enable my video to other person while calling 

i tried this code (in your updated docs) but it is working once only
```
// Add a video track
TVILocalVideoTrack *localVideoTrack = [localMedia addVideoTrack:enable capturer:camera];

// Remove video track
[localMedia removeVideoTrack:localVideoTrack];
```

My usage : 

```
- (IBAction)toggleVideoShare:(id)sender {
 
    if (!videoShareEnable)
    {
        videoShareEnable = YES;
        [self.videoShare setImage:[UIImage imageNamed:@"video_filled.png"] forState:UIControlStateNormal];
        [self.localMedia addVideoTrack:videoShareEnable capturer:self.camera];
    }
    else
    {
        videoShareEnable = NO;
        [self.videoShare setImage:[UIImage imageNamed:@"video_strip.png"] forState:UIControlStateNormal];
        [self.localMedia removeVideoTrack:self.localVideoTrack];
    }
}
```

After disable, enable it and then disable again not working

**Comment by Abhishek9634** [comment]
@ceaglest : Can you helpme on this?

**Comment by ceaglest** [comment]
Hi @Abhishek9634,

You can enable or disable a track after adding it to your `TVILocalMedia`. There is a good example of this for audio tracks in the Quickstart.

https://github.com/twilio/video-quickstart-objc/blob/master/ObjCVideoQuickstart/ViewController.m#L105

You can take the same approach with a `TVILocalVideoTrack`. Here is a snippet which will do this:

```
// Create the enabled track
TVILocalVideoTrack *localVideoTrack = [localMedia addVideoTrack:YES capturer:camera];

// ... Some time later you want to disable the track
localVideoTrack.enabled = NO;
```

Best,
Chris

**Comment by Abhishek9634** [comment]
Thanks now it is working but ur sample project giving one error twilio framework not found
