### ISSUE TITLE
Duplicate participant identity in the same room

### ISSUE THREAD

**Issue by alexiss03** [twilio/video-quickstart-objc#51]
Hi! I would like to know if it is  intended in your that I can connect more than one participant with the same participant identity in the same room? Thanks.

**Comment by ptankTwilio** [comment]
@alexiss03 Yes, at present you can connect more than one participant with the same participant identity in the same Room. Our long term plan is to change this so that Room will have participants with the unique identity.

**Comment by alexiss03** [comment]
I see. Will look forward to this change. Thanks!

**Comment by ptankTwilio** [comment]
@alexiss03 We have fixed this issue where more than one participant can not join the Room with the same identity. Also, we have released with our first Twilio Video SDK 1.0.0 GA release yesterday. I would recommend using the latest release of SDK in your app. Let me know if you have any questions.

**Comment by alexiss03** [comment]
Hi @ptankTwilio! We'll test this change once we updated to Twilio Video SDK 1.0.0 GA release. I'll let you know if we encounter any issues. Thank you!

**Comment by ceaglest** [comment]
I'm closing out this ticket, but please re-open if you are having any issues with the duplicate identity behavior.
