### ISSUE TITLE
Missing audio when headphones is plugged out in iPad2/iOS9

### ISSUE THREAD

**Issue by alexiss03** [twilio/video-quickstart-objc#61]
Hi,

I am encountering missing audio when headphones is plugged out during an ongoing video call. To replicate, connect two devices of which one was iOS 9 running on an iPad2. Then, connect the headphones to the iPad 2. The audio is successfully rerouted to the headphones but when the headphones is plugged out, the audio is not redirected to the device's built-in speaker. I have replicated the same issue with your demo app. I have also inspected the routing of the AVAudioSession and it gives the AVAudioSessionRouteChangeReasonNoSuitableRouteForCategory which probably caused the error. Hoping for your immediate response. Thanks!

Cheers,
Lexi

**Comment by ceaglest** [comment]
Hi @alexiss03,

Thank you for the report, we will try to reproduce and get back to you. Do you use a particular `TVIAudioOutput` setting to reproduce the issue?

@ptankTwilio this looks pretty similar to https://github.com/twilio/video-quickstart-swift/issues/93, assigning it to you.

Best,
Chris Eagleston

**Comment by alexiss03** [comment]
Hi Chris,

I've tried using `TVIAudioOutputVideoChatDefault` and `TVIAudioOutputVideoChatSpeaker ` for the `TVAudioOutput`. Both produced the same scenario.

Thanks,
Lexi

**Comment by ptankTwilio** [comment]
@alexiss03 We are able to reproduce this problem on iPad 2 running iOS 9.3.5. At present we are working on media APIs and GA release, so we won't have this fixed in beta15. We are planning to fix this immediately after GA. I will let you know when the defect is fixed. Thanks.

**Comment by alexiss03** [comment]
@ptankTwilio Thank you for the update on this issue.

**Comment by paynerc** [comment]
Closing this issue as it is being tracked in https://github.com/twilio/video-quickstart-swift/issues/93
