### ISSUE TITLE
removeRenderer:self.previewView is not working.

### ISSUE THREAD

**Issue by qasimsqm** [twilio/video-quickstart-objc#70]
Problem:
In its example code I added code to turn off and on user's own video. I am calling following code to to turn off video but in vain. 

if (self.localVideoTrack) [self.localVideoTrack removeRenderer:self.previewView]
self.localVideoTrack = nil;

- Above code is not turning off the video. Other participant can still see the other’s video.
- It works for remoteView but not for previewView.

Please help me out I am stuck on this point and finding no help.

**Comment by paynerc** [comment]
Hi there!

In the sample code that you provided, you are only removing the local video track from rendering and then dismissing your local pointer to the object. `TVILocalParticipant` still has a reference to the video track, therefore it is still sending video. You will also want to remove the local video track from your `TVILocalParticipant` object. This can be done by calling `removeVideoTrack:` and providing your `self.localVideoTrack` object. Take a look at `TVILocalParticipant.h` for the operations that you can perform on your local participant.

Let us know if you have any further questions!

Ryan

**Comment by qasimsqm** [comment]
Thanks @paynerc that works
